"""Core module for Fenic."""

from fenic.core.mcp import (
    BoundToolParam,
    ParameterizedToolDefinition,
    ToolParam,
)
from fenic.core.metrics import (
    LMMetrics,
    OperatorMetrics,
    QueryMetrics,
    RMMetrics,
)
from fenic.core.types import (
    ArrayType,
    BooleanType,
    BranchSide,
    ClassDefinition,
    ClassifyExample,
    ClassifyExampleCollection,
    ColumnField,
    DataLike,
    DataLikeType,
    DatasetMetadata,
    DataType,
    DateType,
    DocumentPathType,
    DoubleType,
    EmbeddingType,
    FloatType,
    FuzzySimilarityMethod,
    HtmlType,
    IntegerType,
    JoinExample,
    JoinExampleCollection,
    JsonType,
    KeyPoints,
    MapExample,
    MapExampleCollection,
    MarkdownType,
    Paragraph,
    PredicateExample,
    PredicateExampleCollection,
    QueryResult,
    Schema,
    SemanticSimilarityMetric,
    StringType,
    StructField,
    StructType,
    TimestampType,
    TranscriptType,
)

__all__ = [
    # Types
    "ArrayType",
    "BooleanType",
    "BranchSide",
    "DataType",
    "DateType",
    "DocumentPathType",
    "DoubleType",
    "EmbeddingType",
    "FloatType",
    "HtmlType",
    "IntegerType",
    "JsonType",
    "MarkdownType",
    "StringType",
    "StructField",
    "StructType",
    "TimestampType",
    "TranscriptType",
    "ColumnField",
    "Schema",
    "ClassDefinition",
    "ClassifyExample",
    "ClassifyExampleCollection",
    "JoinExample",
    "JoinExampleCollection",
    "MapExample",
    "MapExampleCollection",
    "PredicateExample",
    "PredicateExampleCollection",
    "SemanticSimilarityMetric",
    "KeyPoints",
    "Paragraph",
    "FuzzySimilarityMethod",
    # Metrics
    "QueryMetrics",
    "LMMetrics",
    "RMMetrics",
    "OperatorMetrics",
    # QueryResult
    "DataLike",
    "DataLikeType",
    "QueryResult",
    # Catalog/Schema
    "DatasetMetadata",
    # MCP
    "ToolParam",
    "BoundToolParam",
    "ParameterizedToolDefinition",
]
